eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: apigateway

server:
  port: 8080
spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: company-service
          uri: lb://COMPANYSERVICE
          predicates:
            - Path=/api/v1.0/market/company/**, /company/**
          filters:
            - RewritePath=/company/(?<path>.*), /$\{path}
        - id: stock-service
          uri: lb://STOCKSERVICE
          predicates:
            - Path=/api/v1.0/market/stock/**, /stock/**
          filters:
            - RewritePath=/stock/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs     

springdoc:
  swagger-ui:
    urls:
      - name: company
        url: /v3/api-docs/company
      - name: stock
        url: /v3/api-docs/stock